version: 2

before:
  hooks:
    - go mod tidy
    - go mod vendor
    - go mod verify

builds:
  - id: cursor-id-modifier
    main: ./cmd/cursor-id-modifier/main.go
    binary: cursor-id-modifier
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64, "386"]
    ignore:
      - goos: darwin
        goarch: "386"
    ldflags:
      - -s -w
      - -X 'main.version={{.Version}}'
      - -X 'main.commit={{.ShortCommit}}'
      - -X 'main.date={{.CommitDate}}'
      - -X 'main.builtBy=goreleaser'
    flags: [-trimpath]
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: binary
    format: binary
    name_template: "{{- .ProjectName }}_{{- .Version }}_{{- .Os }}_{{- if eq .Arch \"amd64\" }}x86_64{{- else if eq .Arch \"386\" }}i386{{- else }}{{ .Arch }}{{ end }}"
    builds: [cursor-id-modifier]
    allow_different_binary_count: true
    files: [none*]

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

release:
  draft: false
  prerelease: false
  mode: replace
  header: |
    ## {{.ProjectName}} {{.Tag}} ({{.Date}})
    
    This release includes new features, improvements, and bug fixes.
    See [CHANGELOG.md](CHANGELOG.md) for details.
    
    ### Installation
    
    **Windows**:
    ```powershell
    irm https://raw.githubusercontent.com/{{.Env.GITHUB_REPOSITORY}}/master/scripts/install.ps1 | iex
    ```
    
    **Linux/macOS**:
    ```bash
    curl -fsSL https://raw.githubusercontent.com/{{.Env.GITHUB_REPOSITORY}}/master/scripts/install.sh | sudo bash
    ```
  footer: |
    ### SHA-256 Checksums
    ```
    {{ .Checksums }}
    ```
    
    **Full Changelog**: https://github.com/{{.Env.GITHUB_REPOSITORY}}/compare/{{ .PreviousTag }}...{{ .Tag }}
  extra_files:
    - glob: 'LICENSE*'
    - glob: 'README*'
    - glob: 'CHANGELOG*'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch
      - '^chore:'
  groups:
    - title: '🚀 Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: '🐛 Bug Fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: '🔧 Maintenance'
      regexp: "^.*refactor[(\\w)]*:+.*$"
      order: 2
    - title: '📝 Others'
      order: 999

project_name: cursor-id-modifier
