version: 2

before:
  hooks:
    - go mod tidy
    - go mod verify

builds:
  - id: cursor-id-modifier
    main: ./cmd/cursor-id-modifier/main.go
    binary: cursor-id-modifier
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: arm64
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X 'main.version={{.Version}}'
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: windows
    name_template: "go-cursor-help_windows"
    format: binary
    builds:
      - cursor-id-modifier
    wrap_in_directory: false
    files:
      - none*
    allow_different_binary_count: true
    replacements:
      windows: Windows
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: binary

  - id: macos
    name_template: "go-cursor-help_macos"
    format: binary
    builds:
      - cursor-id-modifier
    wrap_in_directory: false
    files:
      - none*
    allow_different_binary_count: true
    replacements:
      darwin: macOS
    format_overrides:
      - goos: darwin
        format: binary

  - id: linux
    name_template: "go-cursor-help_linux"
    format: binary
    builds:
      - cursor-id-modifier
    wrap_in_directory: false
    files:
      - none*
    allow_different_binary_count: true
    replacements:
      linux: Linux
      amd64: x86_64
    format_overrides:
      - goos: linux
        format: binary

universal_binaries:
  - replace: true
    name_template: "{{ .ProjectName }}"
    ids:
      - cursor-id-modifier

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

release:
  draft: false
  prerelease: false
  mode: replace
  header: |
    ## Release {{.Tag}} ({{.Date}})
  extra_files:
    - glob: 'LICENSE*'
    - glob: 'README*'

project_name: cursor-id-modifier
