version: 2

before:
  hooks:
    - go mod tidy
    - go mod verify

builds:
  - id: cursor-id-modifier
    main: ./cmd/cursor-id-modifier/main.go
    binary: cursor-id-modifier
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: arm64
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X 'main.version={{.Version}}'
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: binary-unix
    name_template: >-
      {{ .ProjectName }}_
      {{- if eq .Os "darwin" }}macOS{{ else }}{{ title .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}_
      {{- .Version }}
    format: binary
    builds:
      - cursor-id-modifier
    files:
      - none*
    allow_different_binary_count: true
    format_overrides:
      - goos: windows
        format: zip

universal_binaries:
  - replace: true
    name_template: "{{ .ProjectName }}_macOS_universal_{{ .Version }}"
    ids:
      - cursor-id-modifier

checksum:
  name_template: 'checksums_{{ .Version }}.txt'
  algorithm: sha256

release:
  draft: false
  prerelease: false
  mode: replace
  name_template: "Release {{.Tag}}"
  header: |
    ## Release {{.Tag}} ({{.Date}})
    
    This is the {{.Tag}} release of cursor-id-modifier.

    ### Quick Installation

    #### Unix/macOS
    ```bash
    curl -fsSL https://raw.githubusercontent.com/yuaotian/go-cursor-help/master/scripts/install.sh | sudo bash
    ```

    #### Windows (PowerShell)
    ```powershell
    Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/yuaotian/go-cursor-help/master/scripts/install.ps1'))
    ```
  extra_files:
    - glob: 'LICENSE*'
    - glob: 'README*'
  replace_existing_draft: true
  skip_upload: false

project_name: cursor-id-modifier

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch
