version: 2

before:
  hooks:
    - go mod tidy
    - go mod verify

builds:
  - id: cursor-id-modifier
    main: ./cmd/cursor-id-modifier/main.go
    binary: cursor-id-modifier
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: arm64
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X 'main.version={{.Version}}'
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: windows
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}_
      {{- .Version }}
    format: binary
    builds:
      - cursor-id-modifier
    files:
      - none*
    allow_different_binary_count: true
    format_overrides:
      - goos: windows
        format: binary

  - id: macos
    name_template: >-
      {{ .ProjectName }}_
      {{- if eq .Os "darwin" }}macOS{{ else }}{{ title .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}_
      {{- .Version }}
    format: binary
    builds:
      - cursor-id-modifier
    files:
      - none*
    allow_different_binary_count: true
    format_overrides:
      - goos: darwin
        format: binary

  - id: linux
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}_
      {{- .Version }}
    format: binary
    builds:
      - cursor-id-modifier
    files:
      - none*
    allow_different_binary_count: true
    format_overrides:
      - goos: linux
        format: binary

universal_binaries:
  - replace: true
    name_template: "{{ .ProjectName }}_{{ .Version }}"
    ids:
      - cursor-id-modifier

checksum:
  name_template: 'checksums_{{ .Version }}.txt'
  algorithm: sha256

release:
  draft: false
  prerelease: false
  mode: replace
  header: |
    ## Release {{.Tag}} ({{.Date}})
  extra_files:
    - glob: 'LICENSE*'
    - glob: 'README*'

project_name: cursor-id-modifier
